application: math-hammer 
version: dev
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static
- url: .*
  script: main.py
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
